var = {};

var(1,:) = {"Antwort_ID","Datum_abgeschickt","letzte_Seite","Sprache_Start","Zufallswert","Datum_Start","Datum_last_activity",...
    "Welcome_Text","group","VPN_Code","Geschlecht","Geschlechtsidentitaet","Alter","hoechste_Ausbildung","hoechste_Ausbildung_sonstiges",...
    "Fachgebiet_Abschluss","Studenten_Sprache_A","Studenten_Sprache_B","Studenten_Sprache_C","U_Sprache_Arbeit_A","U_Sprache_Arbeit_B",...
    "U_Sprache_Arbeit_C","D_Sprache_Arbeit_A","D_Sprache_Arbeit_B","D_Sprache_Arbeit_C","Jahre_Berufserfahrung","prof_Sprachmittler",...
    "Beschreibung_Taetigkeit_Sprachmittler","Berufsbeschaeftigungssituation","Berufsbeschaeftigungssituation_sonstiges","U_Beschaeftigungsgrad",...
    "D_TageletztesJahr","Jahre_aktuelle_Konstellation","Kunden","Kunden_sonstiges","D_Prozent_Community","D_Prozent_Gerichts","D_Prozent_Konsekutiv",...
    "Prozent_Post-Editing","Prozent_Revidieren","D_Prozent_Simultan","U_Prozent","Prozent_Sonstiges","Beschreibung_Sonstiges",...
    "Erfahrung_andere_Bereiche","Kommentar_andere_Bereiche","avghpw_DodU_17-19J","avghpw_DodU_20-22J","avghpw_DodU_23-25J","avghpw_DodU_26-28J",...
    "avghpw_DodU_29-31J","avghpw_DodU_32-34J","avghpw_DodU_35-37J","avghpw_DodU_38-40J","avghpw_DodU_41-43J","avghpw_DodU_44-46J","avghpw_DodU_47-49J",...
    "avghpw_DodU_50-52J","avghpw_DodU_53-55J","avghpw_DodU_56-58J","avghpw_DodU_59-61J","avghpw_DodU_62-64J","avghpw_DodU_65+J",...
    "Chinesisch","Deutsch/Schweizerdeutsch","Franzoesisch","Englisch","Italienisch","weitere_Sprachen","zS1_zusätzlicheSprache","zS1_Alter",...
    "zS1_heute","zS1_hpw_letztesJahr","zS2_zusätzlicheSprache","zS2_Alter","zS2_heute","zS2_hpw_letztesJahr","zS3_zusätzlicheSprache","zS3_Alter",...
    "zS3_heute","zS3_hpw_letztesJahr","zS4_zusätzlicheSprache","zS4_Alter","zS4_heute","zS4_hpw_letztesJahr","zS5_zusätzlicheSprache",...
    "zS5_Alter",    "zS5_heute",    "zS5_hpw_letztesJahr",    "zS6_zusätzlicheSprache",    "zS6_Alter",    "zS6_heute",    "zS6_hpw_letztesJahr",...
    "Alter_DE",    "Familie_DE",    "Schule_DE",    "Sprachkurs_DE",    "Freunde_DE",    "Sprachtandem_DE",    "Familie_Ausland_DE",...
    "Au-Pair_DE",    "Sprachaufenthalt_DE",    "berufl_Ausland_DE",    "Ausland_Studium_DE",    "Sonstiges_DE",    "DE_im_Alltag",...
    "DE_im_Alltag_Sonstiges",    "lesen_DE",    "schreiben_DE",    "verstehen_DE",    "sprechen_DE",    "Verwendung_Sonstiges_DE",...
    "avghpw_Wachzeit_DE_ausgesetzt",    "avghpw_letztesJahr_sprechen_DE",    "avghpw_letztesJahr_lesen_DE",    "avghpw_letztesJahr_hoeren_DE",...
    "Anmerkungen_DE",    "Alter_E",    "Familie_E",    "Schule_E",    "Sprachkurs_E",    "Freunde_E",    "Sprachtandem_E",    "Familie_Ausland_E",...
    "Au-Pair_E",    "Sprachaufenthalt_E",    "berufl_Ausland_E",    "Ausland_Studium_E",    "Sonstiges_E",    "E_im_Alltag",    "E_im_Alltag_Sonstiges",...
    "lesen_E",    "schreiben_E",    "verstehen_E",    "sprechen_E",    "Verwendung_Sonstiges_E",    "avghpw_Wachzeit_E_ausgesetzt",...
    "avghpw_letztesJahr_sprechen_E",    "avghpw_letztesJahr_lesen_E",    "avghpw_letztesJahr_hoeren_E",    "Anmerkungen_E",    "Alter_F",...
    "Familie_F",    "Schule_F",    "Sprachkurs_F",    "Freunde_F",    "Sprachtandem_F",    "Familie_Ausland_F",    "Au-Pair_F",...
    "Sprachaufenthalt_F",    "berufl_Ausland_F",    "Ausland_Studium_F",    "Sonstiges_F",    "F_im_Alltag",    "F_im_Alltag_Sonstiges",    "lesen_F",...
    "schreiben_F",    "verstehen_F",    "sprechen_F",    "Verwendung_Sonstiges_F",    "avghpw_Wachzeit_F_ausgesetzt",...
    "avghpw_letztesJahr_sprechen_F",    "avghpw_letztesJahr_lesen_F",    "avghpw_letztesJahr_hoeren_F",    "Anmerkungen_F",    "Alter_I",  ...
    "Familie_I",    "Schule_I",    "Sprachkurs_I",    "Freunde_I",    "Sprachtandem_I",    "Familie_Ausland_I",    "Au-Pair_I",    "Sprachaufenthalt_I",...
    "berufl_Ausland_I",    "Ausland_Studium_I",    "Sonstiges_I",    "I_im_Alltag",    "I_im_Alltag_Sonstiges",    "lesen_I",    "schreiben_I",...
    "verstehen_I",    "sprechen_I",    "Verwendung_Sonstiges_I",    "avghpw_Wachzeit_I_ausgesetzt",    "avghpw_letztesJahr_sprechen_I",...
    "avghpw_letztesJahr_lesen_I",    "avghpw_letztesJahr_hoeren_I",    "Anmerkungen_I",    "Alter_CN",    "Familie_CN",    "Schule_CN",...
    "Sprachkurs_CN",    "Freunde_CN",    "Sprachtandem_CN",    "Familie_Ausland_CN",    "Au-Pair_CN",    "Sprachaufenthalt_CN",    "berufl_Ausland_CN",...
    "Ausland_Studium_CN",    "Sonstiges_CN",    "CN_im_Alltag",    "CN_im_Alltag_Sonstiges",    "lesen_CN",    "schreiben_CN",    "verstehen_CN",...
    "sprechen_CN",    "Verwendung_Sonstiges_CN",    "avghpw_Wachzeit_CN_ausgesetzt",    "avghpw_letztesJahr_sprechen_CN",...
    "avghpw_letztesJahr_lesen_CN",    "avghpw_letztesJahr_hoeren_CN",    "Anmerkungen_CN",    "Erstsprache/n",    "Erstsprache_Eltern1",...
    "Erstsprache_Eltern2","Instument_ueb_Schule",    "Hauptinstrument",    "HI_sonstiges",    "Alter_HI",    "HI_letztes_Jahr",    "Alter_Ende_HI",...
    "hpw_letzesJahr_HI",    "spielt_Zweitinstrument",    "Zweitinstrument",    "ZI_sonstiges",    "Alter_ZI",    "ZI_letztes_Jahr",    "Alter_Ende_ZI",...
    "hpw_letzesJahr_ZI",    "avghpw_Musi_0-7J",    "avghpw_Musi_8-10J",    "avghpw_Musi_11-13J",    "avghpw_Musi_14-16J",    "avghpw_Musi_17-19J",...
    "avghpw_Musi_20-22J",    "avghpw_Musi_23-25J",    "avghpw_Musi_26-28J",    "avghpw_Musi_29-31J",    "avghpw_Musi_32-34J",    "avghpw_Musi_35-37J",...
    "avghpw_Musi_38-40J",    "avghpw_Musi_41-43J",    "avghpw_Musi_44-46J",    "avghpw_Musi_47-49J",    "avghpw_Musi_50-52J",    "avghpw_Musi_53-55J",...
    "avghpw_Musi_56-58J",    "avghpw_Musi_59-61J",    "avghpw_Musi_62-64J",    "avghpw_Musi_65+J",    "Freizeit_Musik_Hoeren",    "hpd_letztesJahr_Musikhoeren",...
    "Absolutes_Gehoer",    "Kommentar_musikalischer_Werdegang", "Anmerkungen"};

pers_factors = [1, 4, 9, 10, 11, 14, 15, 16];
dol_factors = [2:10, 12, 14, 19, 30]+15;
spr_factors = [2:8,10:2:30,33:44,46:50,57:68,70:74,81:92,94:98,105:116,118:122,129:140,142:146,152:154]+62;
mus_factors = [2:4, 6, 9:11, 13, 37, 39]+215;

dol_numeric = [11, 16, 18, 20:28, 32:48]+15;
spr_numeric = [9:2:31,32,51:54,56,75:78,80,99:102,104,123:126,128,147:150]+62;
mus_numeric = [5, 7, 8, 12, 14:36, 38]+215;

dol_char = [13, 15, 29, 31]+15;
spr_char = [45, 55, 69, 79, 93, 103, 117, 127, 141, 151]+62;
mus_char = [40]+215;

for i = 1:256
    var(2,i) = {i};
    if sum(i == pers_factors)>0 || sum(i == dol_factors)>0 || sum(i == spr_factors)>0 || sum(i == mus_factors)>0
        var(3,i) = {1};        
    end
    if sum(i == dol_numeric)>0 || sum(i == spr_numeric)>0 || sum(i == mus_numeric)>0
        var(4,i) = {1};        
    end
    if  sum(i == dol_char)>0 || sum(i == spr_char)>0 || sum(i == mus_char)>0
        var(5,i) = {1};        
    end    
end

factor = [];
numeric = [];
char = [];

for i = 1:256
    if var{3,i} == 1
        factor = [factor,var(2,i)];
    elseif var{4,i} == 1
        numeric = [numeric,var(2,i)];
    elseif var{5,i} == 1
        char = [char,var(2,i)];
    end
end
   
